QiuDaBao/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'QiuDaBao.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^', include('index.urls', namespace='index')),

    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    url(r'^qiudabao/', include('qiudabao.urls', namespace='qiudabao')),
)

accounts/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

urlpatterns = patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login',
      { 'template_name': 'accounts/login.html' }, name='login'),

    url(r'^logout/$', 'django.contrib.auth.views.logout', 
      { 'template_name': 'accounts/logout.html' }, name='logout'),

    url(r'^profile/$', TemplateView.as_view(
      template_name='accounts/profile.html'), name='profile'),
)

index/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='index/index.html'),
      name='index'),
)

qiudabao/urls.py
from django.conf.urls import patterns, include, url

from qiudabao.views import user_register, OrderListView
from qiudabao.views import account_balance
from qiudabao.views import UserOfferedOrders, UserSubmittedOrders
from qiudabao.views import OfferOrder, submit_order, confirm_order

urlpatterns = patterns('',

    url(r'^register/$', user_register, name='register'),

    url(r'^account_balance/$', account_balance, name='account_balance'),

    url(r'^order_list/$', OrderListView.as_view(), name='order_list'),

    url(r'^user_offered_order_list/$', UserOfferedOrders.as_view(),
      name='user_offered_order_list'),

    url(r'^user_submitted_order_list/$', UserSubmittedOrders.as_view(),
      name='user_submitted_order_list'),

    url(r'^offer_order/$', OfferOrder.as_view(), name='offer_order'),

    url(r'^submit_order/$', submit_order, name='submit_order'),

    url(r'^confirm_order/$', confirm_order, name='confirm_order'),
)

index/models.py
from django.db import models

qiudabao/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class AccountInfo(models.Model):
  user    = models.ForeignKey(User)
  balance = models.IntegerField()

DISH_NAME_MAX_LENGTH = 20

class Order(models.Model):
  offerer     = models.ForeignKey(User, related_name='offerer_order')
  submiter    = models.ForeignKey(User, related_name='submiter_order', null=True, blank=True)
  dish        = models.CharField(max_length=DISH_NAME_MAX_LENGTH)
  description = models.TextField(blank=True)
  place       = models.TextField()

qiudabao/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms

class UserRegisterForm(forms.Form):
  username = forms.CharField(max_length=100)
  password = forms.CharField(widget=forms.PasswordInput)

accounts/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

index/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

qiudabao/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.contrib.auth.models import User
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views.decorators.http import require_POST
from django.views.generic import ListView
from django.views.generic.edit import CreateView

from qiudabao.forms import UserRegisterForm
from qiudabao.models import AccountInfo, Order

# Create your views here.

def user_register(request):
  if request.method == 'POST':
    form = UserRegisterForm(request.POST)
    if (form.is_valid()):
      uname = form.cleaned_data['username']
      psw   = form.cleaned_data['password']
      user  = User.objects.create_user(username=uname, password=psw)
      user.save()
      account = AccountInfo(user=user, balance=100)
      account.save()
      return HttpResponseRedirect(reverse('accounts:profile'))
  else: # GET
    form = UserRegisterForm()
  return render(request, 'qiudabao/register.html', { 'form': form })

def account_balance(request):
  accountinfo = AccountInfo.objects.get(user=request.user)
  context     = { 'accountinfo': accountinfo }
  return render(request, 'qiudabao/account_balance.html', context)

# All orders
class OrderListView(ListView):
  queryset            = Order.objects.filter(submiter=None)
  context_object_name = 'orders'
  template_name       = 'qiudabao/order_list.html'

# User offered orders
class UserOfferedOrders(ListView):
  context_object_name = 'orders'
  template_name       = 'qiudabao/user_offered_order_list.html'

  def get_queryset(self):
    orders = Order.objects.filter(offerer=self.request.user)
    return orders

# User submitted orders
class UserSubmittedOrders(ListView):
  context_object_name = 'orders'
  template_name       = 'qiudabao/user_submitted_order_list.html'

  def get_queryset(self):
    orders = Order.objects.filter(submiter=self.request.user)
    return orders

class OfferOrder(CreateView):
  model         = Order
  fields        = [ 'dish', 'description', 'place' ]
  template_name = 'qiudabao/offer_order.html'
  success_url   = reverse_lazy('qiudabao:order_list')

  def form_valid(self, form):
    # TODO: underflow case
    account = AccountInfo.objects.get(user=self.request.user)
    account.balance -= 1
    account.save()
    order = form.save(commit=False)
    order.offerer = self.request.user
    return super(OfferOrder, self).form_valid(form)

@require_POST
def submit_order(request):
  try:
    _id = request.POST.get('order_id')
    order = Order.objects.get(id=_id)
    order.submiter = request.user
    order.save()
  except: # FIXME, KeyError or objects get error
    raise Http404
  return HttpResponseRedirect(reverse('qiudabao:order_list'))

@require_POST
def confirm_order(request):
  try:
    _id = request.POST.get('order_id')
    order = Order.objects.get(id=_id)
    account = AccountInfo.objects.get(user=order.submiter)
    account.balance += 1
    account.save()
    order.delete()
  except Exception as ex:
    return HttpResponse(str(ex))
    raise Http404
  return HttpResponseRedirect(reverse('qiudabao:user_offered_order_list'))

accounts/templates/accounts/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>

<body>
  {% if form.errors %}
  <p>Your username and password didn't match. Please try again.</p>
  {% endif %}

  <form method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    <table>
      <tr>
         <td>{{ form.username.label_tag }}</td>
         <td>{{ form.username }}</td>
      </tr>
      <tr>
        <td>{{ form.password.label_tag }}</td>
        <td>{{ form.password }}</td>
      </tr>
    </table>
    <input type="submit" value="login" />
    <input type="hidden" name="next" value="{{ next }}" />
  </form>

</body>
</html>

accounts/templates/accounts/logout.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>

<body>
  <div>
    <p>You have already logged out, :)</p>
  </div>
</body>
</html>

accounts/templates/accounts/profile.html
<h1> user profile </h1>

<a href="{% url 'qiudabao:order_list' %}">Orders Nearby</a>

<a href="{% url 'qiudabao:offer_order' %}">Order</a>

<a href="{% url 'qiudabao:account_balance' %}">Balance</a>

index/templates/index/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html dir="ltr" lang="en">
<head>
  <title>
    Qiu Da Bao
  </title>
</head>
<body>
  <h1>
    Qiu Da Bao, Welcome to Qiu Da Bao!
  </h1>
  <p> Please <a href="{% url 'accounts:login' %}">login</a> first!</p>
  <p> Or <a href="{% url 'accounts:profile' %}">go profile</a>!</p>
</body>
</html>

qiudabao/templates/qiudabao/account_balance.html
<html>
<body>
  <p> {{ accountinfo.balance }} </p>
</body>
</html>

qiudabao/templates/qiudabao/offer_order.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
  <head>
  </head>
  <body>
    <h2>User Register</h2>

    <form method="POST" action="{% url 'qiudabao:offer_order' %}">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Offer order" />

    </form>
  </body>
</html>

qiudabao/templates/qiudabao/order_list.html
<h2>all orders</h2>

<a href="{% url 'qiudabao:offer_order' %}">Order</a>

{% for order in orders %}
<p>{{ order.dish }} {{ order.description }}</p>
<form method="POST" action="{% url 'qiudabao:submit_order' %}">
  {% csrf_token %}
  <input type="hidden" name="order_id" value="{{ order.id }}" />
  <input type="submit" value="submit order" />
</form>
{% endfor %}

qiudabao/templates/qiudabao/register.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
  <head>
  </head>
  <body>
    <h2>User Register</h2>

    <form method="POST" action="{% url 'qiudabao:register' %}">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="login" />

    </form>
  </body>
</html>

qiudabao/templates/qiudabao/user_offered_order_list.html
<h2> orders i offered </h2>

<a href="{% url 'qiudabao:offer_order' %}">Order</a>

{% for order in orders %}
<p>{{ order.dish }} {{ order.description }}</p>
<form method="POST" action="{% url 'qiudabao:confirm_order' %}">
  {% csrf_token %}
  <input type="hidden" name="order_id" value="{{ order.id }}" />
  <input type="submit" value="confirm order" />
</form>
{% endfor %}

qiudabao/templates/qiudabao/user_submitted_order_list.html
<h2>what i submitted</h2>

<a href="{% url 'qiudabao:offer_order' %}">Order</a>

{% for order in orders %}
<p>{{ order.dish }} {{ order.description }}</p>
{% endfor %}